# Generated by Django 4.0.4 on 2024-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('isbn', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
